# -*- mode: ruby -*-
# vi: set ft=ruby :

#Parte 1 - Vagrant

Vagrant.configure("2") do |config|

  # Configuração da VM1 (Veridis)
  config.vm.define "veridis" do |veridis|
    veridis.vm.box = "debian/buster64"
    veridis.vm.network "private_network", virtualbox__intnet: "intnet1", auto_config: false
    veridis.vm.network "private_network", virtualbox__intnet: "intnet2", auto_config: false
    veridis.vm.hostname = "Server-Veridis"
    veridis.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "Server-Veridis"
      vb.gui = false
      vb.customize ['createhd', '--filename', 'diskz1z.vdi', '--size', '10240']
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'diskz1z.vdi']
      vb.customize ['createhd', '--filename', 'diskz2z.vdi', '--size', '10240']
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', 'diskz2z.vdi']
      vb.customize ['createhd', '--filename', 'diskz3z.vdi', '--size', '10240']
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', 'diskz3z.vdi']
    end

    # Configuração de provisionamento do Veridis com Ansible
    veridis.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_veridis.yml"
    end
  end



  # # Configuração da VM2 (Statusquo)
  # config.vm.define "statusquo" do |statusquo|
  #   statusquo.vm.box = "debian/buster64"
  #   statusquo.vm.network "private_network", virtualbox__intnet: "intnet1", auto_config: false
  #   statusquo.vm.network "private_network", virtualbox__intnet: "intnet2", auto_config: false
  #   statusquo.vm.hostname = "Server-Statusquo"
  #   statusquo.vm.provider "virtualbox" do |vb|
  #     vb.memory = "1024"
  #     vb.name = "Server-Statusquo"
  #     vb.gui = false
  #   end

  #   # Configuração de provisionamento com Ansible
  #   statusquo.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "playbook_statusquo.yml"
  #   end
  # end

  # Configuração da VM3 (Client)
  config.vm.define "client" do |client|
    client.vm.box = "debian/buster64"
    client.vm.network "private_network", virtualbox__intnet: "intnet1", auto_config: false #interface for lan
    client.vm.network "private_network", virtualbox__intnet: "intnet2", auto_config: false #interface for wan
    client.vm.hostname = "Client-Host"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "Client-Host"
      vb.gui = false
    end

    # Configuração de provisionamento com Ansible
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_client.yml"
    end
  end

end

  
