# -*- mode: ruby -*-
# vi: set ft=ruby :

#Parte 1 - Vagrant

Vagrant.configure("2") do |config|

  # Configuração da VM1 (Veridis)
  config.vm.define "veridis" do |veridis|
    veridis.vm.box = "debian/buster64"
    veridis.vm.network "private_network", virtualbox__intnet: "intnet", auto_config: false #interface private for lan
    veridis.vm.network "private_network", virtualbox__intnet: "intnet", auto_config: false #interface private for wan
    veridis.vm.hostname = "Server-Veridis"
    veridis.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "Server-Veridis"
      vb.gui = false
      vb.customize ['createhd', '--filename', 'diskz1z.vdi', '--size', '10240']
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'diskz1z.vdi']
      vb.customize ['createhd', '--filename', 'diskz2z.vdi', '--size', '10240']
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', 'diskz2z.vdi']
      vb.customize ['createhd', '--filename', 'diskz3z.vdi', '--size', '10240']
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', 'diskz3z.vdi']
      
      # Add host-only network adapter (#5)
      #vb.customize ['modifyvm', :id, '--nic5', 'hostonly']
      #vb.customize ['modifyvm', :id, '--hostonlyadapter5', 'vboxnet0']
      #vb.customize ['modifyvm', :id, '--nicpromisc5', 'allow-all']
      #vb.customize ['modifyvm', :id, '--hostonlyadapter6', 'vboxnet0']

    end
    #host-only network WAN (comunication between VM and host)
    #veridis.vm.provision "shell", inline: <<-SHELL
    #  echo "auto eth4" >> /etc/network/interfaces
    #  echo "iface eth4 inet static" >> /etc/network/interfaces
    #  echo "address 192.168.57.8" >> /etc/network/interfaces
    #  echo "netmask 255.255.255.0" >> /etc/network/interfaces
    #  ifup eth4
    #SHELL

    #host-only network LAN (comunication between VM and host)
    veridis.vm.network "private_network", ip: "192.168.57.7"

    # Configuração de provisionamento do Veridis com Ansible
    veridis.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_veridis.yml"
    end
  end



  # Configuração da VM2 (Statusquo)
  config.vm.define "statusquo" do |statusquo|
    statusquo.vm.box = "debian/buster64"
    statusquo.vm.network "private_network", virtualbox__intnet: "intnet", auto_config: false
    statusquo.vm.network "private_network", virtualbox__intnet: "intnet", auto_config: false
    statusquo.vm.hostname = "Server-Statusquo"
    statusquo.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "Server-Statusquo"
      vb.gui = false
    end

    # Configuração de provisionamento com Ansible
    statusquo.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_statusquo.yml"
    end
  end


  # Configuração da VM3 (Client)
  config.vm.define "client" do |client|
    client.vm.box = "debian/buster64"
    client.vm.network "private_network", virtualbox__intnet: "intnet", auto_config: false #interface for lan
    client.vm.network "private_network", virtualbox__intnet: "intnet", auto_config: false #interface for wan
    client.vm.hostname = "Client-Host"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "Client-Host"
      vb.gui = false
    end

    # Configuração de provisionamento com Ansible
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_client.yml"
    end
  end

end

  
