FROM debian:latest

# Install nginx openssl and ssl-cert
RUN apt-get update && apt-get install -y nginx openssl ssl-cert iputils-ping dnsutils nano

# Copy the configuration nginx files
COPY default /etc/nginx/sites-available/

# Define the correct permissions nginx
RUN chown root:root /etc/nginx/sites-available/default

# Create the directory for certificate https in default path nginx
RUN mkdir -p /etc/nginx/certificado

# Create the certificate https
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certificado/abranteme.key -out /etc/nginx/certificado/abranteme.crt -subj "/C=BR/ST=PB/L=PB/O=Abranteme Corp/OU=Departamento de Desenvolvimento/CN=abranteme.com.br"

# Create error50x directory in /var/www/
RUN mkdir -p /var/www/error

# Copy the 50x error files
COPY Network-Services-Structure/isolated_environment/imagem_for_dockerhub_veridis/nginx/lan/pgs_error/custom_50x.html /var/www/error/

# Expose the necessary ports
EXPOSE 443

# Start service
CMD ["nginx", "-g", "daemon off;"]

