FROM debian:latest

# Install Apache
RUN apt-get update && apt-get install -y apt-utils apache2 iputils-ping dnsutils nano

# Copy configuration files
COPY ports.conf /etc/apache2/
COPY apache2.conf /etc/apache2/
COPY app01.abranteme.com.br.conf /etc/apache2/sites-available/
COPY app02.abranteme.com.br.conf /etc/apache2/sites-available/

# Create directories
RUN mkdir -p /dados/www/app01
RUN mkdir -p /dados/www/app02/jornal
RUN mkdir -p /etc/apache2/senhas/app02

# Copy files
COPY app01/index.html /dados/www/app01/
COPY 404.html /dados/www/app01/
COPY 404.html /dados/www/app02/
COPY app02/index.html /dados/www/app02/
COPY app02/jornal/hi.txt /dados/www/app02/jornal/
COPY app02/jornal/login.html /dados/www/app02/

# Create user and password
RUN htpasswd -c -b /etc/apache2/senhas/app02/abranteme.htpasswd abranteme abranteme 

# Define the correct permissions
RUN chown -R www-data:www-data /dados/www/app01
RUN chown -R www-data:www-data /dados/www/app02
RUN chown -R www-data:www-data /etc/apache2/senhas/app02

# Enable the necessary modules
RUN a2enmod auth_form request session session_cookie session_crypto

# Enable the necessary sites
RUN a2ensite app01.abranteme.com.br.conf
RUN a2ensite app02.abranteme.com.br.conf

# Expose the necessary ports
EXPOSE 80

# Restart service
CMD ["apachectl", "-D", "FOREGROUND"]

